/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateGroupTypeArgs } from "./CreateGroupTypeArgs";
import { UpdateGroupTypeArgs } from "./UpdateGroupTypeArgs";
import { DeleteGroupTypeArgs } from "./DeleteGroupTypeArgs";
import { GroupTypeFindManyArgs } from "./GroupTypeFindManyArgs";
import { GroupTypeFindUniqueArgs } from "./GroupTypeFindUniqueArgs";
import { GroupType } from "./GroupType";
import { GroupTypeService } from "../groupType.service";

@graphql.Resolver(() => GroupType)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class GroupTypeResolverBase {
  constructor(
    protected readonly service: GroupTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GroupType",
    action: "read",
    possession: "any",
  })
  async _groupTypesMeta(
    @graphql.Args() args: GroupTypeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [GroupType])
  @nestAccessControl.UseRoles({
    resource: "GroupType",
    action: "read",
    possession: "any",
  })
  async groupTypes(
    @graphql.Args() args: GroupTypeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<GroupType[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "GroupType",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => GroupType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GroupType",
    action: "read",
    possession: "own",
  })
  async groupType(
    @graphql.Args() args: GroupTypeFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<GroupType | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "GroupType",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => GroupType)
  @nestAccessControl.UseRoles({
    resource: "GroupType",
    action: "create",
    possession: "any",
  })
  async createGroupType(
    @graphql.Args() args: CreateGroupTypeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<GroupType> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "GroupType",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"GroupType"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => GroupType)
  @nestAccessControl.UseRoles({
    resource: "GroupType",
    action: "update",
    possession: "any",
  })
  async updateGroupType(
    @graphql.Args() args: UpdateGroupTypeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<GroupType | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "GroupType",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"GroupType"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GroupType)
  @nestAccessControl.UseRoles({
    resource: "GroupType",
    action: "delete",
    possession: "any",
  })
  async deleteGroupType(
    @graphql.Args() args: DeleteGroupTypeArgs
  ): Promise<GroupType | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
