/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { UserUpdateManyWithoutEmpowermentsInput } from "./UserUpdateManyWithoutEmpowermentsInput";
import {
  ValidateNested,
  IsOptional,
  IsBoolean,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { EmpowermentHistoryUpdateManyWithoutEmpowermentsInput } from "./EmpowermentHistoryUpdateManyWithoutEmpowermentsInput";
import { ResourceUpdateManyWithoutEmpowermentsInput } from "./ResourceUpdateManyWithoutEmpowermentsInput";
@InputType()
class EmpowermentUpdateInput {
  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutEmpowermentsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutEmpowermentsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutEmpowermentsInput, {
    nullable: true,
  })
  authorizedTeachers?: UserUpdateManyWithoutEmpowermentsInput;

  @ApiProperty({
    required: false,
    type: () => EmpowermentHistoryUpdateManyWithoutEmpowermentsInput,
  })
  @ValidateNested()
  @Type(() => EmpowermentHistoryUpdateManyWithoutEmpowermentsInput)
  @IsOptional()
  @Field(() => EmpowermentHistoryUpdateManyWithoutEmpowermentsInput, {
    nullable: true,
  })
  empowermentHistories?: EmpowermentHistoryUpdateManyWithoutEmpowermentsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isDeleted?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ResourceUpdateManyWithoutEmpowermentsInput,
  })
  @ValidateNested()
  @Type(() => ResourceUpdateManyWithoutEmpowermentsInput)
  @IsOptional()
  @Field(() => ResourceUpdateManyWithoutEmpowermentsInput, {
    nullable: true,
  })
  resource?: ResourceUpdateManyWithoutEmpowermentsInput;
}
export { EmpowermentUpdateInput };
