/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateEmpowermentArgs } from "./CreateEmpowermentArgs";
import { UpdateEmpowermentArgs } from "./UpdateEmpowermentArgs";
import { DeleteEmpowermentArgs } from "./DeleteEmpowermentArgs";
import { EmpowermentFindManyArgs } from "./EmpowermentFindManyArgs";
import { EmpowermentFindUniqueArgs } from "./EmpowermentFindUniqueArgs";
import { Empowerment } from "./Empowerment";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { EmpowermentHistoryFindManyArgs } from "../../empowermentHistory/base/EmpowermentHistoryFindManyArgs";
import { EmpowermentHistory } from "../../empowermentHistory/base/EmpowermentHistory";
import { ResourceFindManyArgs } from "../../resource/base/ResourceFindManyArgs";
import { Resource } from "../../resource/base/Resource";
import { EmpowermentService } from "../empowerment.service";

@graphql.Resolver(() => Empowerment)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class EmpowermentResolverBase {
  constructor(
    protected readonly service: EmpowermentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Empowerment",
    action: "read",
    possession: "any",
  })
  async _empowermentsMeta(
    @graphql.Args() args: EmpowermentFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Empowerment])
  @nestAccessControl.UseRoles({
    resource: "Empowerment",
    action: "read",
    possession: "any",
  })
  async empowerments(
    @graphql.Args() args: EmpowermentFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Empowerment[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Empowerment",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Empowerment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Empowerment",
    action: "read",
    possession: "own",
  })
  async empowerment(
    @graphql.Args() args: EmpowermentFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Empowerment | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Empowerment",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Empowerment)
  @nestAccessControl.UseRoles({
    resource: "Empowerment",
    action: "create",
    possession: "any",
  })
  async createEmpowerment(
    @graphql.Args() args: CreateEmpowermentArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Empowerment> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Empowerment",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Empowerment"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Empowerment)
  @nestAccessControl.UseRoles({
    resource: "Empowerment",
    action: "update",
    possession: "any",
  })
  async updateEmpowerment(
    @graphql.Args() args: UpdateEmpowermentArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Empowerment | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Empowerment",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Empowerment"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Empowerment)
  @nestAccessControl.UseRoles({
    resource: "Empowerment",
    action: "delete",
    possession: "any",
  })
  async deleteEmpowerment(
    @graphql.Args() args: DeleteEmpowermentArgs
  ): Promise<Empowerment | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "Empowerment",
    action: "read",
    possession: "any",
  })
  async authorizedTeachers(
    @graphql.Parent() parent: Empowerment,
    @graphql.Args() args: UserFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const results = await this.service.findAuthorizedTeachers(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [EmpowermentHistory])
  @nestAccessControl.UseRoles({
    resource: "Empowerment",
    action: "read",
    possession: "any",
  })
  async empowermentHistories(
    @graphql.Parent() parent: Empowerment,
    @graphql.Args() args: EmpowermentHistoryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EmpowermentHistory[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "EmpowermentHistory",
    });
    const results = await this.service.findEmpowermentHistories(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Resource])
  @nestAccessControl.UseRoles({
    resource: "Empowerment",
    action: "read",
    possession: "any",
  })
  async resource(
    @graphql.Parent() parent: Empowerment,
    @graphql.Args() args: ResourceFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Resource[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Resource",
    });
    const results = await this.service.findResource(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
