/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DiscussionThreadUpdateManyWithoutDiscussionThreadsInput } from "./DiscussionThreadUpdateManyWithoutDiscussionThreadsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { DiscussionForumWhereUniqueInput } from "../../discussionForum/base/DiscussionForumWhereUniqueInput";
import { DiscussionThreadWhereUniqueInput } from "./DiscussionThreadWhereUniqueInput";
@InputType()
class DiscussionThreadUpdateInput {
  @ApiProperty({
    required: false,
    type: () => DiscussionThreadUpdateManyWithoutDiscussionThreadsInput,
  })
  @ValidateNested()
  @Type(() => DiscussionThreadUpdateManyWithoutDiscussionThreadsInput)
  @IsOptional()
  @Field(() => DiscussionThreadUpdateManyWithoutDiscussionThreadsInput, {
    nullable: true,
  })
  childDiscussionThreads?: DiscussionThreadUpdateManyWithoutDiscussionThreadsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  comment?: string | null;

  @ApiProperty({
    required: false,
    type: () => DiscussionForumWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DiscussionForumWhereUniqueInput)
  @IsOptional()
  @Field(() => DiscussionForumWhereUniqueInput, {
    nullable: true,
  })
  discussionForum?: DiscussionForumWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DiscussionThreadWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DiscussionThreadWhereUniqueInput)
  @IsOptional()
  @Field(() => DiscussionThreadWhereUniqueInput, {
    nullable: true,
  })
  parentThread?: DiscussionThreadWhereUniqueInput | null;
}
export { DiscussionThreadUpdateInput };
