/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnnouncementWhereUniqueInput } from "../../announcement/base/AnnouncementWhereUniqueInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { DiscussionForumCreateNestedManyWithoutGroupsInput } from "./DiscussionForumCreateNestedManyWithoutGroupsInput";
import { EnumGroupGroupType } from "./EnumGroupGroupType";
import { ResourceCreateNestedManyWithoutGroupsInput } from "./ResourceCreateNestedManyWithoutGroupsInput";
import { UserCreateNestedManyWithoutGroupsInput } from "./UserCreateNestedManyWithoutGroupsInput";
@InputType()
class GroupCreateInput {
  @ApiProperty({
    required: false,
    type: () => AnnouncementWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AnnouncementWhereUniqueInput)
  @IsOptional()
  @Field(() => AnnouncementWhereUniqueInput, {
    nullable: true,
  })
  announcement?: AnnouncementWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  details?: string | null;

  @ApiProperty({
    required: false,
    type: () => DiscussionForumCreateNestedManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => DiscussionForumCreateNestedManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => DiscussionForumCreateNestedManyWithoutGroupsInput, {
    nullable: true,
  })
  discussionForums?: DiscussionForumCreateNestedManyWithoutGroupsInput;

  @ApiProperty({
    required: true,
    enum: EnumGroupGroupType,
  })
  @IsEnum(EnumGroupGroupType)
  @Field(() => EnumGroupGroupType)
  groupType!: "System" | "Default";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => ResourceCreateNestedManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => ResourceCreateNestedManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => ResourceCreateNestedManyWithoutGroupsInput, {
    nullable: true,
  })
  resources?: ResourceCreateNestedManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutGroupsInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutGroupsInput;
}
export { GroupCreateInput };
