/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnnouncementWhereUniqueInput } from "../../announcement/base/AnnouncementWhereUniqueInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { DiscussionForumUpdateManyWithoutGroupsInput } from "./DiscussionForumUpdateManyWithoutGroupsInput";
import { EnumGroupGroupType } from "./EnumGroupGroupType";
import { ResourceUpdateManyWithoutGroupsInput } from "./ResourceUpdateManyWithoutGroupsInput";
import { UserUpdateManyWithoutGroupsInput } from "./UserUpdateManyWithoutGroupsInput";
@InputType()
class GroupUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AnnouncementWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AnnouncementWhereUniqueInput)
  @IsOptional()
  @Field(() => AnnouncementWhereUniqueInput, {
    nullable: true,
  })
  announcement?: AnnouncementWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  details?: string | null;

  @ApiProperty({
    required: false,
    type: () => DiscussionForumUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => DiscussionForumUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => DiscussionForumUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  discussionForums?: DiscussionForumUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    enum: EnumGroupGroupType,
  })
  @IsEnum(EnumGroupGroupType)
  @IsOptional()
  @Field(() => EnumGroupGroupType, {
    nullable: true,
  })
  groupType?: "System" | "Default";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ResourceUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => ResourceUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => ResourceUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  resources?: ResourceUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutGroupsInput;
}
export { GroupUpdateInput };
