/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMahakramaHistoryArgs } from "./CreateMahakramaHistoryArgs";
import { UpdateMahakramaHistoryArgs } from "./UpdateMahakramaHistoryArgs";
import { DeleteMahakramaHistoryArgs } from "./DeleteMahakramaHistoryArgs";
import { MahakramaHistoryFindManyArgs } from "./MahakramaHistoryFindManyArgs";
import { MahakramaHistoryFindUniqueArgs } from "./MahakramaHistoryFindUniqueArgs";
import { MahakramaHistory } from "./MahakramaHistory";
import { MahakramaFindManyArgs } from "../../mahakrama/base/MahakramaFindManyArgs";
import { Mahakrama } from "../../mahakrama/base/Mahakrama";
import { User } from "../../user/base/User";
import { MahakramaHistoryService } from "../mahakramaHistory.service";

@graphql.Resolver(() => MahakramaHistory)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MahakramaHistoryResolverBase {
  constructor(
    protected readonly service: MahakramaHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MahakramaHistory",
    action: "read",
    possession: "any",
  })
  async _mahakramaHistoriesMeta(
    @graphql.Args() args: MahakramaHistoryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [MahakramaHistory])
  @nestAccessControl.UseRoles({
    resource: "MahakramaHistory",
    action: "read",
    possession: "any",
  })
  async mahakramaHistories(
    @graphql.Args() args: MahakramaHistoryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MahakramaHistory[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "MahakramaHistory",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => MahakramaHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MahakramaHistory",
    action: "read",
    possession: "own",
  })
  async mahakramaHistory(
    @graphql.Args() args: MahakramaHistoryFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MahakramaHistory | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "MahakramaHistory",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => MahakramaHistory)
  @nestAccessControl.UseRoles({
    resource: "MahakramaHistory",
    action: "create",
    possession: "any",
  })
  async createMahakramaHistory(
    @graphql.Args() args: CreateMahakramaHistoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MahakramaHistory> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "MahakramaHistory",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"MahakramaHistory"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        student: {
          connect: args.data.student,
        },
      },
    });
  }

  @graphql.Mutation(() => MahakramaHistory)
  @nestAccessControl.UseRoles({
    resource: "MahakramaHistory",
    action: "update",
    possession: "any",
  })
  async updateMahakramaHistory(
    @graphql.Args() args: UpdateMahakramaHistoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MahakramaHistory | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "MahakramaHistory",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"MahakramaHistory"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          student: {
            connect: args.data.student,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MahakramaHistory)
  @nestAccessControl.UseRoles({
    resource: "MahakramaHistory",
    action: "delete",
    possession: "any",
  })
  async deleteMahakramaHistory(
    @graphql.Args() args: DeleteMahakramaHistoryArgs
  ): Promise<MahakramaHistory | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Mahakrama])
  @nestAccessControl.UseRoles({
    resource: "MahakramaHistory",
    action: "read",
    possession: "any",
  })
  async mahakrama(
    @graphql.Parent() parent: MahakramaHistory,
    @graphql.Args() args: MahakramaFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Mahakrama[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Mahakrama",
    });
    const results = await this.service.findMahakrama(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MahakramaHistory",
    action: "read",
    possession: "any",
  })
  async student(
    @graphql.Parent() parent: MahakramaHistory,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getStudent(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
