/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMahakramaArgs } from "./CreateMahakramaArgs";
import { UpdateMahakramaArgs } from "./UpdateMahakramaArgs";
import { DeleteMahakramaArgs } from "./DeleteMahakramaArgs";
import { MahakramaFindManyArgs } from "./MahakramaFindManyArgs";
import { MahakramaFindUniqueArgs } from "./MahakramaFindUniqueArgs";
import { Mahakrama } from "./Mahakrama";
import { MahakramaHistoryFindManyArgs } from "../../mahakramaHistory/base/MahakramaHistoryFindManyArgs";
import { MahakramaHistory } from "../../mahakramaHistory/base/MahakramaHistory";
import { ResourceFindManyArgs } from "../../resource/base/ResourceFindManyArgs";
import { Resource } from "../../resource/base/Resource";
import { MahakramaService } from "../mahakrama.service";

@graphql.Resolver(() => Mahakrama)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MahakramaResolverBase {
  constructor(
    protected readonly service: MahakramaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Mahakrama",
    action: "read",
    possession: "any",
  })
  async _mahakramasMeta(
    @graphql.Args() args: MahakramaFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Mahakrama])
  @nestAccessControl.UseRoles({
    resource: "Mahakrama",
    action: "read",
    possession: "any",
  })
  async mahakramas(
    @graphql.Args() args: MahakramaFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Mahakrama[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Mahakrama",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Mahakrama, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Mahakrama",
    action: "read",
    possession: "own",
  })
  async mahakrama(
    @graphql.Args() args: MahakramaFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Mahakrama | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Mahakrama",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Mahakrama)
  @nestAccessControl.UseRoles({
    resource: "Mahakrama",
    action: "create",
    possession: "any",
  })
  async createMahakrama(
    @graphql.Args() args: CreateMahakramaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Mahakrama> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Mahakrama",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Mahakrama"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Mahakrama)
  @nestAccessControl.UseRoles({
    resource: "Mahakrama",
    action: "update",
    possession: "any",
  })
  async updateMahakrama(
    @graphql.Args() args: UpdateMahakramaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Mahakrama | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Mahakrama",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Mahakrama"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Mahakrama)
  @nestAccessControl.UseRoles({
    resource: "Mahakrama",
    action: "delete",
    possession: "any",
  })
  async deleteMahakrama(
    @graphql.Args() args: DeleteMahakramaArgs
  ): Promise<Mahakrama | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [MahakramaHistory])
  @nestAccessControl.UseRoles({
    resource: "Mahakrama",
    action: "read",
    possession: "any",
  })
  async mahakramaHistories(
    @graphql.Parent() parent: Mahakrama,
    @graphql.Args() args: MahakramaHistoryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<MahakramaHistory[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "MahakramaHistory",
    });
    const results = await this.service.findMahakramaHistories(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Resource])
  @nestAccessControl.UseRoles({
    resource: "Mahakrama",
    action: "read",
    possession: "any",
  })
  async resource(
    @graphql.Parent() parent: Mahakrama,
    @graphql.Args() args: ResourceFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Resource[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Resource",
    });
    const results = await this.service.findResource(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
