/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ResourceUpdateManyWithoutResourcesInput } from "./ResourceUpdateManyWithoutResourcesInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { EmpowermentUpdateManyWithoutResourcesInput } from "./EmpowermentUpdateManyWithoutResourcesInput";
import { EventWhereUniqueInput } from "../../event/base/EventWhereUniqueInput";
import { GroupUpdateManyWithoutResourcesInput } from "./GroupUpdateManyWithoutResourcesInput";
import { MahakramaUpdateManyWithoutResourcesInput } from "./MahakramaUpdateManyWithoutResourcesInput";
import { ResourceWhereUniqueInput } from "./ResourceWhereUniqueInput";
import { EnumResourceResourceType } from "./EnumResourceResourceType";
@InputType()
class ResourceUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ResourceUpdateManyWithoutResourcesInput,
  })
  @ValidateNested()
  @Type(() => ResourceUpdateManyWithoutResourcesInput)
  @IsOptional()
  @Field(() => ResourceUpdateManyWithoutResourcesInput, {
    nullable: true,
  })
  childResources?: ResourceUpdateManyWithoutResourcesInput;

  @ApiProperty({
    required: false,
    type: () => EmpowermentUpdateManyWithoutResourcesInput,
  })
  @ValidateNested()
  @Type(() => EmpowermentUpdateManyWithoutResourcesInput)
  @IsOptional()
  @Field(() => EmpowermentUpdateManyWithoutResourcesInput, {
    nullable: true,
  })
  empowerments?: EmpowermentUpdateManyWithoutResourcesInput;

  @ApiProperty({
    required: false,
    type: () => EventWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EventWhereUniqueInput)
  @IsOptional()
  @Field(() => EventWhereUniqueInput, {
    nullable: true,
  })
  event?: EventWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => GroupUpdateManyWithoutResourcesInput,
  })
  @ValidateNested()
  @Type(() => GroupUpdateManyWithoutResourcesInput)
  @IsOptional()
  @Field(() => GroupUpdateManyWithoutResourcesInput, {
    nullable: true,
  })
  groups?: GroupUpdateManyWithoutResourcesInput;

  @ApiProperty({
    required: false,
    type: () => MahakramaUpdateManyWithoutResourcesInput,
  })
  @ValidateNested()
  @Type(() => MahakramaUpdateManyWithoutResourcesInput)
  @IsOptional()
  @Field(() => MahakramaUpdateManyWithoutResourcesInput, {
    nullable: true,
  })
  mahakramas?: MahakramaUpdateManyWithoutResourcesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ResourceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ResourceWhereUniqueInput)
  @IsOptional()
  @Field(() => ResourceWhereUniqueInput, {
    nullable: true,
  })
  parentResource?: ResourceWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumResourceResourceType,
  })
  @IsEnum(EnumResourceResourceType)
  @IsOptional()
  @Field(() => EnumResourceResourceType, {
    nullable: true,
  })
  resourceType?: "Image" | "Youtube" | "Document" | "Link" | "Folder" | null;
}
export { ResourceUpdateInput };
