/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ResourceCreateNestedManyWithoutResourcesInput } from "./ResourceCreateNestedManyWithoutResourcesInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { EmpowermentCreateNestedManyWithoutResourcesInput } from "./EmpowermentCreateNestedManyWithoutResourcesInput";
import { EventWhereUniqueInput } from "../../event/base/EventWhereUniqueInput";
import { GroupCreateNestedManyWithoutResourcesInput } from "./GroupCreateNestedManyWithoutResourcesInput";
import { MahakramaCreateNestedManyWithoutResourcesInput } from "./MahakramaCreateNestedManyWithoutResourcesInput";
import { ResourceWhereUniqueInput } from "./ResourceWhereUniqueInput";
import { EnumResourceResourceType } from "./EnumResourceResourceType";
@InputType()
class ResourceCreateInput {
  @ApiProperty({
    required: false,
    type: () => ResourceCreateNestedManyWithoutResourcesInput,
  })
  @ValidateNested()
  @Type(() => ResourceCreateNestedManyWithoutResourcesInput)
  @IsOptional()
  @Field(() => ResourceCreateNestedManyWithoutResourcesInput, {
    nullable: true,
  })
  childResources?: ResourceCreateNestedManyWithoutResourcesInput;

  @ApiProperty({
    required: false,
    type: () => EmpowermentCreateNestedManyWithoutResourcesInput,
  })
  @ValidateNested()
  @Type(() => EmpowermentCreateNestedManyWithoutResourcesInput)
  @IsOptional()
  @Field(() => EmpowermentCreateNestedManyWithoutResourcesInput, {
    nullable: true,
  })
  empowerments?: EmpowermentCreateNestedManyWithoutResourcesInput;

  @ApiProperty({
    required: false,
    type: () => EventWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EventWhereUniqueInput)
  @IsOptional()
  @Field(() => EventWhereUniqueInput, {
    nullable: true,
  })
  event?: EventWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => GroupCreateNestedManyWithoutResourcesInput,
  })
  @ValidateNested()
  @Type(() => GroupCreateNestedManyWithoutResourcesInput)
  @IsOptional()
  @Field(() => GroupCreateNestedManyWithoutResourcesInput, {
    nullable: true,
  })
  groups?: GroupCreateNestedManyWithoutResourcesInput;

  @ApiProperty({
    required: false,
    type: () => MahakramaCreateNestedManyWithoutResourcesInput,
  })
  @ValidateNested()
  @Type(() => MahakramaCreateNestedManyWithoutResourcesInput)
  @IsOptional()
  @Field(() => MahakramaCreateNestedManyWithoutResourcesInput, {
    nullable: true,
  })
  mahakramas?: MahakramaCreateNestedManyWithoutResourcesInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => ResourceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ResourceWhereUniqueInput)
  @IsOptional()
  @Field(() => ResourceWhereUniqueInput, {
    nullable: true,
  })
  parentResource?: ResourceWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumResourceResourceType,
  })
  @IsEnum(EnumResourceResourceType)
  @IsOptional()
  @Field(() => EnumResourceResourceType, {
    nullable: true,
  })
  resourceType?: "Image" | "Youtube" | "Document" | "Link" | "Folder" | null;
}
export { ResourceCreateInput };
