/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateDiscussionForumArgs } from "./CreateDiscussionForumArgs";
import { UpdateDiscussionForumArgs } from "./UpdateDiscussionForumArgs";
import { DeleteDiscussionForumArgs } from "./DeleteDiscussionForumArgs";
import { DiscussionForumFindManyArgs } from "./DiscussionForumFindManyArgs";
import { DiscussionForumFindUniqueArgs } from "./DiscussionForumFindUniqueArgs";
import { DiscussionForum } from "./DiscussionForum";
import { DiscussionThreadFindManyArgs } from "../../discussionThread/base/DiscussionThreadFindManyArgs";
import { DiscussionThread } from "../../discussionThread/base/DiscussionThread";
import { GroupFindManyArgs } from "../../group/base/GroupFindManyArgs";
import { Group } from "../../group/base/Group";
import { DiscussionForumService } from "../discussionForum.service";

@graphql.Resolver(() => DiscussionForum)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DiscussionForumResolverBase {
  constructor(
    protected readonly service: DiscussionForumService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "read",
    possession: "any",
  })
  async _discussionForumsMeta(
    @graphql.Args() args: DiscussionForumFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [DiscussionForum])
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "read",
    possession: "any",
  })
  async discussionForums(
    @graphql.Args() args: DiscussionForumFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DiscussionForum[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DiscussionForum",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => DiscussionForum, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "read",
    possession: "own",
  })
  async discussionForum(
    @graphql.Args() args: DiscussionForumFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DiscussionForum | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "DiscussionForum",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => DiscussionForum)
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "create",
    possession: "any",
  })
  async createDiscussionForum(
    @graphql.Args() args: CreateDiscussionForumArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DiscussionForum> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "DiscussionForum",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DiscussionForum"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => DiscussionForum)
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "update",
    possession: "any",
  })
  async updateDiscussionForum(
    @graphql.Args() args: UpdateDiscussionForumArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DiscussionForum | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "DiscussionForum",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DiscussionForum"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DiscussionForum)
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "delete",
    possession: "any",
  })
  async deleteDiscussionForum(
    @graphql.Args() args: DeleteDiscussionForumArgs
  ): Promise<DiscussionForum | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [DiscussionThread])
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "read",
    possession: "any",
  })
  async discussionThreads(
    @graphql.Parent() parent: DiscussionForum,
    @graphql.Args() args: DiscussionThreadFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DiscussionThread[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DiscussionThread",
    });
    const results = await this.service.findDiscussionThreads(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Group])
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "read",
    possession: "any",
  })
  async group(
    @graphql.Parent() parent: DiscussionForum,
    @graphql.Args() args: GroupFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Group[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Group",
    });
    const results = await this.service.findGroup(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
